name: Build sqlexecutor

on:
  push:
    tags:
      - 'v*'   # 打 tag 如 v1.0.0 时触发
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]

    permissions:
      contents: write  # 上传 release 所需权限

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Extract tag version
        id: get_version
        run: echo "version=${GITHUB_REF##*/}" >> "$GITHUB_OUTPUT"

      - name: Build and zip binary with versioned name
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          VERSION: ${{ steps.get_version.outputs.version }}
        run: |
          mkdir -p dist
          ext=""
          if [ "$GOOS" = "windows" ]; then
            ext=".exe"
          fi

          filename="gosql-executor-${VERSION}-${GOOS}-${GOARCH}${ext}"
          zipname="gosql-executor-${VERSION}-${GOOS}-${GOARCH}.zip"

          # 构建带版本名的二进制
          GOOS=$GOOS GOARCH=$GOARCH go build -o "$filename" ./cmd

          # 打包 zip
          zip -j "dist/$zipname" "$filename"

      - name: Upload release artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
